version: 2

updates:
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: weekly
      day: wednesday
      time: "06:00"
    groups:
      python-dependencies:
        patterns:
          - "*"

  - package-ecosystem: "conda"
    directory: "/"
    schedule:
      interval: weekly
      day: wednesday
      time: "06:00"
    groups:
      conda-dependencies:
        patterns:
          - "*"

  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: weekly
      day: wednesday
      time: "06:00"
    groups:
      npm-dependencies:
        patterns:
          - "*"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: weekly
      day: wednesday
      time: "06:00"
    groups:
      github-actions:
        patterns:
          - "*"
