version: 2

updates:
  - package-ecosystem: pip
    directory: /
    schedule:
      interval: daily
      time: "05:00"
      timezone: "Europe/London"
    groups:
      python-dependencies:
        patterns:
          - "*"
    assignees:
      - frankbuckley

  - package-ecosystem: conda
    directory: /
    schedule:
      interval: daily
      time: "05:00"
      timezone: "Europe/London"
    groups:
      conda-dependencies:
        patterns:
          - "*"
    assignees:
      - frankbuckley

  - package-ecosystem: npm
    directory: /
    schedule:
      interval: daily
      time: "05:00"
      timezone: "Europe/London"
    groups:
      npm-dependencies:
        patterns:
          - "*"
    assignees:
      - frankbuckley

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: daily
      time: "05:00"
      timezone: "Europe/London"
    groups:
      github-actions:
        patterns:
          - "*"
    assignees:
      - frankbuckley
