# Copyright (c) 2026 Down Syndrome Education International and contributors
# SPDX-License-Identifier: AGPL-3.0-or-later

"""Generate cross-platform Conda and exact installed pip lock files."""

from __future__ import annotations

import argparse
import json
import os
import stat
import subprocess
import sys
import tempfile
from pathlib import Path

import yaml

ROOT = Path(__file__).resolve().parents[1]
LOCKFILE = ROOT / "conda-lock.yml"
PIP_LOCKFILE = ROOT / "requirements-pip.lock"
PLATFORMS = ("linux-64", "osx-arm64")


def _run_json(command: list[str], *, env: dict[str, str] | None = None):
    result = subprocess.run(
        command,
        check=True,
        capture_output=True,
        text=True,
        env=env,
    )
    return json.loads(result.stdout)


def _clean_environment() -> dict[str, str]:
    clean = os.environ.copy()
    clean.pop("PYTHONPATH", None)
    return clean


def _conda_executable() -> str:
    return os.environ.get("CONDA_EXE", "conda")


def _environment_prefix(conda: str, environment_name: str) -> Path:
    payload = _run_json([conda, "env", "list", "--json"], env=_clean_environment())
    matches = [
        Path(prefix)
        for prefix in payload["envs"]
        if Path(prefix).name == environment_name
    ]
    if len(matches) != 1:
        raise RuntimeError(
            f"Expected exactly one Conda environment named {environment_name!r}; "
            f"found {len(matches)}."
        )
    return matches[0]


def _write_conda_only_spec(destination: Path) -> None:
    source = yaml.safe_load((ROOT / "environment.yml").read_text(encoding="utf-8"))
    source["dependencies"] = [
        dependency
        for dependency in source["dependencies"]
        if not isinstance(dependency, dict) or "pip" not in dependency
    ]
    destination.write_text(
        yaml.safe_dump(source, sort_keys=False),
        encoding="utf-8",
    )


def _direct_git_requirement(prefix: Path, package_name: str) -> str:
    pattern = package_name.replace("-", "_") + "-*.dist-info/direct_url.json"
    matches = list(prefix.glob(f"lib/python*/site-packages/{pattern}"))
    if len(matches) != 1:
        raise RuntimeError(
            f"Expected one direct_url.json for {package_name}; found {len(matches)}."
        )
    payload = json.loads(matches[0].read_text(encoding="utf-8"))
    vcs = payload.get("vcs_info", {})
    commit = vcs.get("commit_id")
    url = payload.get("url", "")
    subdirectory = payload.get("subdirectory")
    if vcs.get("vcs") != "git" or not commit or not url:
        raise RuntimeError(f"{package_name} is not installed from an exact Git revision.")
    suffix = f"#subdirectory={subdirectory}" if subdirectory else ""
    return f"{package_name}[viz,notebook,io] @ git+{url}@{commit}{suffix}"


def _write_pip_lock(conda: str, environment_name: str, prefix: Path) -> None:
    packages = _run_json(
        [conda, "list", "--name", environment_name, "--json"],
        env=_clean_environment(),
    )
    pypi = sorted(
        (
            package["name"],
            package["version"],
        )
        for package in packages
        if package.get("channel") == "pypi"
        and package["name"] not in {"dse-research-utils", "dse-vocab-growth"}
    )
    lines = [
        "# Generated by scripts/lock_environment.py; do not edit by hand.",
        "# Install after conda-lock.yml, then install this repository with: pip install -e ./",
        _direct_git_requirement(prefix, "dse-research-utils"),
        *(f"{name}=={version}" for name, version in pypi),
        "",
    ]
    PIP_LOCKFILE.write_text("\n".join(lines), encoding="utf-8")


def _normalise_lock_metadata(conda_spec: Path) -> None:
    """Remove the temporary extraction path from generated lock metadata."""
    text = LOCKFILE.read_text(encoding="utf-8")
    lines = []
    for line in text.splitlines():
        if line.startswith("#     conda-lock -f ") and line.endswith(
            " --lockfile conda-lock.yml"
        ):
            lines.append(
                "#     python scripts/lock_environment.py --environment dse-vocab-growth"
            )
        elif line.strip().endswith(str(conda_spec)):
            lines.append("  - environment.yml")
        else:
            lines.append(line)
    LOCKFILE.write_text("\n".join(lines) + "\n", encoding="utf-8")


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--environment",
        default="dse-vocab-growth",
        help="Existing verified environment whose pip layer should be frozen.",
    )
    args = parser.parse_args()
    conda = _conda_executable()
    prefix = _environment_prefix(conda, args.environment)

    subprocess.run(
        [conda, "run", "--name", args.environment, "dse-check-env", "environment.yml"],
        cwd=ROOT,
        check=True,
        env=_clean_environment(),
    )

    with tempfile.TemporaryDirectory(prefix="vocab-growth-lock-") as temporary:
        temporary_path = Path(temporary)
        conda_spec = temporary_path / "environment-conda.yml"
        _write_conda_only_spec(conda_spec)
        conda_wrapper = temporary_path / "conda-clean"
        conda_wrapper.write_text(
            "#!/usr/bin/env bash\nunset PYTHONPATH\nexec "
            + json.dumps(conda)
            + " \"$@\"\n",
            encoding="utf-8",
        )
        conda_wrapper.chmod(conda_wrapper.stat().st_mode | stat.S_IXUSR)
        command = [
            sys.executable,
            "-m",
            "conda_lock",
            "lock",
            "--file",
            str(conda_spec),
            "--lockfile",
            str(LOCKFILE),
            "--without-cuda",
            "--conda",
            str(conda_wrapper),
        ]
        for platform_name in PLATFORMS:
            command.extend(["--platform", platform_name])
        subprocess.run(command, cwd=ROOT, check=True)
        _normalise_lock_metadata(conda_spec)

    _write_pip_lock(conda, args.environment, prefix)
    print(f"Wrote {LOCKFILE.relative_to(ROOT)} for {', '.join(PLATFORMS)}")
    print(f"Wrote {PIP_LOCKFILE.relative_to(ROOT)} from {args.environment}")


if __name__ == "__main__":
    main()
